// Script Power Query para crear la tabla de dimensión de tiempo personalizada (dimTiempo)
// La granularidad es a nivel de segundos, genera una tabla con 86400 filas
// Adaptado de: https://radacad.com/script-for-creating-time-table-in-power-bi-with-hours-minutes-and-seconds-buckets
let
    Fuente = List.Times(#time(0,0,0),24*60*60,#duration(0,0,0,1)),
    #"Convertida a Tabla" = Table.FromList(Fuente, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Columnas Renombradas" = Table.RenameColumns(#"Convertida a Tabla",{{"Column1", "Hora"}}),
    #"Tipo Cambiado" = Table.TransformColumnTypes(#"Columnas Renombradas",{{"Hora", type time}}),
    #"Hora Insertada" = Table.AddColumn(#"Tipo Cambiado", "HoraNum", each Time.Hour([Hora]), Int64.Type),
    #"Minuto Insertado" = Table.AddColumn(#"Hora Insertada", "Minuto", each Time.Minute([Hora]), Int64.Type),
    #"Segundo Insertado" = Table.AddColumn(#"Minuto Insertado", "Segundo", each Time.Second([Hora]), type number),
    #"Columna Condicional Añadida" = Table.AddColumn(#"Segundo Insertado", "AM/PM", each if [HoraNum] < 12 then "a.m." else "p.m."),
    #"Tipo Cambiado1" = Table.TransformColumnTypes(#"Columna Condicional Añadida",{{"AM/PM", type text}}),
    #"Columna Duplicada" = Table.DuplicateColumn(#"Tipo Cambiado1", "Hora", "Hora - Copia"),
    #"Columnas Eliminadas" = Table.RemoveColumns(#"Columna Duplicada",{"Hora - Copia"}),
    #"Columna Duplicada1" = Table.DuplicateColumn(#"Columnas Eliminadas", "HoraNum", "HoraNum - Copia"),
    #"Columnas Renombradas1" = Table.RenameColumns(#"Columna Duplicada1",{{"HoraNum - Copia", "Etiqueta Hora"}}),
    #"Tipo Cambiado2" = Table.TransformColumnTypes(#"Columnas Renombradas1",{{"Etiqueta Hora", type text}}),
    #"Columnas Eliminadas1" = Table.RemoveColumns(#"Tipo Cambiado2",{"Etiqueta Hora"}),
    #"Prefijo Insertado" = Table.AddColumn(#"Columnas Eliminadas1", "Prefijo", each "0" & Text.From([HoraNum], "en-NZ"), type text),
    #"Columnas Renombradas2" = Table.RenameColumns(#"Prefijo Insertado",{{"Prefijo", "Etiqueta Hora"}}),
    #"Últimos Caracteres Extraídos" = Table.TransformColumns(#"Columnas Renombradas2", {{"Etiqueta Hora", each Text.End(_, 2), type text}}),
    #"Prefijo Insertado1" = Table.AddColumn(#"Últimos Caracteres Extraídos", "Prefijo", each "0" & Text.From([Minuto], "en-NZ"), type text),
    #"Columnas Renombradas3" = Table.RenameColumns(#"Prefijo Insertado1",{{"Prefijo", "Etiqueta Minuto"}}),
    #"Últimos Caracteres Extraídos1" = Table.TransformColumns(#"Columnas Renombradas3", {{"Etiqueta Minuto", each Text.End(_, 2), type text}}),
    #"Prefijo Insertado2" = Table.AddColumn(#"Últimos Caracteres Extraídos1", "Prefijo", each "0" & Text.From([Segundo], "en-NZ"), type text),
    #"Columnas Renombradas4" = Table.RenameColumns(#"Prefijo Insertado2",{{"Prefijo", "Etiqueta Segundo"}}),
    #"Últimos Caracteres Extraídos2" = Table.TransformColumns(#"Columnas Renombradas4", {{"Etiqueta Segundo", each Text.End(_, 2), type text}}),
    #"Índice Añadido" = Table.AddIndexColumn(#"Últimos Caracteres Extraídos2", "Índice", 0, 1),
    #"Columnas Renombradas5" = Table.RenameColumns(#"Índice Añadido",{{"Índice", "Clave Tiempo"}}),
    #"Módulo Insertado" = Table.AddColumn(#"Columnas Renombradas5", "Módulo", each Number.Mod([HoraNum], 12), type number),
    #"Columnas Renombradas6" = Table.RenameColumns(#"Módulo Insertado",{{"Módulo", "Bin Hora 12"}}),
    #"División Entera Insertada" = Table.AddColumn(#"Columnas Renombradas6", "División Entera", each Number.IntegerDivide([HoraNum], 8), Int64.Type),
    #"Columnas Renombradas7" = Table.RenameColumns(#"División Entera Insertada",{{"División Entera", "Bin Hora 8"}}),
    #"División Entera Insertada1" = Table.AddColumn(#"Columnas Renombradas7", "División Entera", each Number.IntegerDivide([HoraNum], 6), Int64.Type),
    #"Columnas Renombradas8" = Table.RenameColumns(#"División Entera Insertada1",{{"División Entera", "Bin Hora 6"}}),
    #"División Entera Insertada2" = Table.AddColumn(#"Columnas Renombradas8", "División Entera", each Number.IntegerDivide([HoraNum], 4), Int64.Type),
    #"Columnas Renombradas9" = Table.RenameColumns(#"División Entera Insertada2",{{"División Entera", "Bin Hora 4"}}),
    #"División Entera Insertada3" = Table.AddColumn(#"Columnas Renombradas9", "División Entera", each Number.IntegerDivide([HoraNum], 3), Int64.Type),
    #"Columnas Renombradas10" = Table.RenameColumns(#"División Entera Insertada3",{{"División Entera", "Bin Hora 3"}}),
    #"División Entera Insertada4" = Table.AddColumn(#"Columnas Renombradas10", "División Entera", each Number.IntegerDivide([HoraNum], 2), Int64.Type),
    #"Columnas Renombradas11" = Table.RenameColumns(#"División Entera Insertada4",{{"División Entera", "Bin Hora 2"}}),
    #"División Entera Insertada5" = Table.AddColumn(#"Columnas Renombradas11", "División Entera", each Number.IntegerDivide([Minuto], 30), Int64.Type),
    #"Columna Multiplicada" = Table.TransformColumns(#"División Entera Insertada5", {{"División Entera", each _ * 30, type number}}),
    #"Columnas Renombradas12" = Table.RenameColumns(#"Columna Multiplicada",{{"División Entera", "Bin Minuto 30"}}),
    #"División Entera Insertada6" = Table.AddColumn(#"Columnas Renombradas12", "División Entera", each Number.IntegerDivide([Minuto], 15), Int64.Type),
    #"Columna Multiplicada1" = Table.TransformColumns(#"División Entera Insertada6", {{"División Entera", each _ * 15, type number}}),
    #"Columnas Renombradas13" = Table.RenameColumns(#"Columna Multiplicada1",{{"División Entera", "Bin Minuto 15"}}),
    #"División Entera Insertada7" = Table.AddColumn(#"Columnas Renombradas13", "División Entera", each Number.IntegerDivide([Minuto], 10), Int64.Type),
    #"Columna Multiplicada2" = Table.TransformColumns(#"División Entera Insertada7", {{"División Entera", each _ * 10, type number}}),
    #"Columnas Renombradas14" = Table.RenameColumns(#"Columna Multiplicada2",{{"División Entera", "Bin Minuto 10"}}),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas Renombradas14",{{"Segundo", Int64.Type}, {"Clave Tiempo", Int64.Type}, {"Bin Hora 12", Int64.Type}, {"Bin Minuto 15", Int64.Type}, {"Bin Minuto 30", Int64.Type}, {"Bin Minuto 10", Int64.Type}})
in
    #"Tipo cambiado"